import PostDetails from '../../components/posts/post-details'
import { GetAllPostPaths, GetPostData } from '../../libs/post-utils'
import Head from 'next/head'
function Post(props) {
    const { post } = props;

    return (
        <>
            <Head>
                <title>{post.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PostDetails post={post} />
        </>
    )
}


export async function getStaticProps(context) {
    const { params } = context;
    const { id } = params;
    const post = await GetPostData(id)
    return {
        props: { post }
    }
}

export async function getStaticPaths() {
    const postIds = await GetAllPostPaths();
    const paths = postIds.map(id => ({ params: { id: id.toString() } }));

    return {
        paths,
        fallback: false
    }
}
export default Post;