import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PostGrid from '../components/posts/post-grid'

import HomeLongFeaturedPost from '../components/posts/home-long-featured-post'
import Footer from '../components/layout/footer'
import { GetAllPosts } from '../libs/post-utils'
import Layout from '../components/layout/Layout'

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Darabseh Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <HomeLongFeaturedPost />


      <PostGrid posts={props.posts} />
    </>
  )
}

export async function getStaticProps() {
  const allPosts = await GetAllPosts();
  return {
    props: {
      posts: allPosts,
    },
  };

}
