import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PostGrid from '../components/posts/post-grid'
import Intro from '../components/home-page/intro'
import Footer from '../components/layout/footer'
import {GetAllPosts} from '../libs/post-utils'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Darabseh Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Intro />
          <PostGrid posts={props.posts}/>

      </main>

    <Footer/>
    </div>
  )
}

export async function getStaticProps(){
const allPosts = await GetAllPosts();
return {
  props: {
    posts: allPosts,
  },
};

}
